jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Build with Maven
      run: ./mvnw -B verify
    - continue-on-error: true
      name: Upload to Codecov
      uses: codecov/codecov-action@v2.0.2
      with:
        file: ./target/site/jacoco/jacoco.xml
        flags: unittests
        token: ${{ secrets.CODECOV_TOKEN }}
    - continue-on-error: true
      name: Upload to Codecov (ITest)
      uses: codecov/codecov-action@v2.0.2
      with:
        file: ./target/site/jacoco-it/jacoco.xml
        flags: integrationtests
        token: ${{ secrets.CODECOV_TOKEN }}
name: Build master with Maven
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
